# Generated by Django 4.0.4 on 2022-04-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Runner',
        ),
    ]
