# Generated by Django 4.0.4 on 2022-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashing', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='hash',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
